# Generated by Django 5.1.1 on 2024-09-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('Estrela', 'ESTRELA'), ('Galaxia', 'GALAXIA'), ('Planeta', 'PLANETA')], default='', max_length=100),
        ),
    ]
